GadgetsShop/ViewModels/ShopCartViewModel.cs
using GadgetsShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GadgetsShop.ViewModels
{
    /// <summary>
    /// This class provides an access to the current shop cart
    /// </summary>
    public class ShopCartViewModel
    {
        //Field
        private ShopCart shopCart;

        //Property
        public ShopCart ShopCart { get => shopCart; set => shopCart = value; }
    }
}

GadgetsShop/Controllers/OrderController.cs
using GadgetsShop.Data;
using GadgetsShop.Data.Interfaces;
using GadgetsShop.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GadgetsShop.Controllers
{
    /// <summary>
    /// This class provides an order's controller
    /// </summary>
    public class OrderController : Controller
    {
        //Fields
        private readonly IAllOrders _allOrders;
        private readonly ShopCart _shopCart;

        //Constructor
        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this._allOrders = allOrders;
            this._shopCart = shopCart;
        }

        /// <summary>
        /// This method finds and returns the HTML-page with the name of the method.
        /// </summary>
        /// <param name="order">Order item</param>
        /// <returns>The HTML-page from the Views/Order repository</returns>
        public IActionResult Checkout()
        {
            return View();
        }

        /// <summary>
        /// This method finds and returns the HTML-page with the name of the method.
        /// </summary>
        /// <param name="order">Order item</param>
        /// <returns>The HTML-page from the Views/Order repository</returns>
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            _shopCart.ListShopItems = _shopCart.GetShopItems();

            if(_shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError("", "Нет товаров в корзине!");
            }

            if(ModelState.IsValid)
            {
                _allOrders.CreateOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        /// <summary>
        /// This method finds and returns the HTML-page with the name of the method.
        /// </summary>
        /// <returns>The HTML-page from the Views/Order repository</returns>
        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

GadgetsShop/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GadgetsShop.Data.Interfaces;
using GadgetsShop.Data.Models;
using GadgetsShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GadgetsShop.Controllers
{
    /// <summary>
    /// This class provides an shopcart's controller
    /// </summary>
    public class ShopCartController : Controller
    {
        //Fields
        private readonly IAllGadgets _gadgRep;
        private readonly ShopCart _shopCart;

        //Constructor
        public ShopCartController(IAllGadgets gadgetRepository, ShopCart shopCart)
        {
            _gadgRep = gadgetRepository;
            _shopCart = shopCart;
        }
        /// <summary>
        /// This method finds and returns the HTML-page with the name of the method.
        /// </summary>
        /// <returns>The HTML-page from the Views/ShopCart repository</returns>
        public ViewResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;
            var obj = new ShopCartViewModel { ShopCart = _shopCart };
           
            return View(obj);
        }
        /// <summary>
        /// This method processes the gadget's adding to the basket.
        /// </summary>
        /// <param name="id">A gadget' id</param>
        /// <returns>Redirection to the following HTML-page.</returns>
        public RedirectToActionResult AddToCart(int id)
        {
            Gadget item = _gadgRep.GetGadgets.FirstOrDefault(i => i.Id == id);
            if(item!=null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }

        /// <summary>
        /// This method processes the gadget's removing from the basket.
        /// </summary>
        /// <param name="shopCartItem">An item of the basket</param>
        /// <returns>Redirection to the following HTML-page.</returns>
        public RedirectToActionResult RemoveFromCart(ShopCartItem shopCartItem)
        {
            if(shopCartItem != null)
            {
                _shopCart.RemoveFromCart(shopCartItem);
            }

            return RedirectToAction("Index");
        }
    }
}

GadgetsShop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel

@{
    string connStr = "Server=(localdb)\\MSSQLLocalDB;Database=GadgetsShop;Trusted_Connection=True;MultipleActiveResultSets=true";
    int totalSum = 0;
}
    <h1>Корзина</h1>
    <div class="container">
        @foreach (var el in Model.ShopCart.ListShopItems)
        {
        <div class="alert alert-warning mt-3">
            @{
                string gadgID = "";
                string price = "";
                string name = "";


                GadgetsShop.SqlWorker sqlWorker = new GadgetsShop.SqlWorker(connStr);
                gadgID = sqlWorker.SelectDataFromDB("SELECT gadgetid FROM ShopCartItem WHERE id=" + el.Id);
                name = sqlWorker.SelectDataFromDB("SELECT name FROM Gadget WHERE id=" + gadgID);
                price = sqlWorker.SelectDataFromDB("SELECT price FROM Gadget WHERE id=" + gadgID);

                int gadgPrice = Convert.ToInt32(price);
                totalSum += gadgPrice;

            }
            <b>Гаджет:</b>@name<br />
            <b>Цена:</b>@price BYN
            <p><a class="btn btn-warning button-delete" asp-controller="ShopCart" asp-action="RemoveFromCart" asp-route-id="@el.Id">Удалить из корзины</a></p>
        </div>

        }
        <p>Иготовая сумма: @totalSum BYN</p>
        <hr />
        <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Оплатить</a>
    </div>